stages:
  - check
  - build
  - test
  - deploy

variables:
  # The name of the Flatpak module of our app.
  FLATPAK_MODULE: "fractal"
  # The path to the Flatpak manifest.
  MANIFEST_PATH: "build-aux/org.gnome.Fractal.Devel.json"
  # The ID of our Flatpak app.
  APP_ID: "org.gnome.Fractal.Devel"
  # The latest GNOME stable Flatpak runtime.
  GNOME_STABLE_VERSION: "50"
  # The version of the Freedesktop.org Flatpak runtime used by the stable GNOME runtime.
  FREEDESKTOP_RUNTIME_BRANCH: "25.08"


workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

include:
  - local: .gitlab-ci/check.yml
  - local: .gitlab-ci/build.yml
  - local: .gitlab-ci/test.yml
  - component: "gitlab.gnome.org/GNOME/citemplates/basic-deploy-docs@master"
    inputs:
      docs-job-name: "build-docs"
  - local: .gitlab-ci/publish_nightly.yml
    rules:
      - if: $CI_COMMIT_BRANCH == "main"
