#!/bin/sh
# Turn `build-aux/android/gstreamer-plugins` into a link line or into C.
#
#     sh gstreamer-static-plugins.sh <prefix-arch-dir> <plugin-list> --libs
#     sh gstreamer-static-plugins.sh <prefix-arch-dir> <plugin-list> --source
#
# `<prefix-arch-dir>` is one architecture of the prefix `gstreamer-prefix.sh`
# builds — e.g. `~/android/gst-android/x86_64`. Everything this script names
# comes out of that prefix's `deps/`.
#
# Called from `meson.build` at configure time. One list feeds both outputs so
# that a plugin cannot be linked without being registered, or registered
# without being linked — the first is dead weight, the second is a link error.
#
# # Registration is ours to call
#
# The ndk-build template shipped in `share/gst-android/ndk-build` writes a
# `gst_init_static_plugins()` and says it is called by `gst_init()`. In this
# tarball it is not: nothing in `libgstreamer-1.0.a` references that symbol at
# all. It is a convention of that template's own init function, and since we do
# not use the template, registration is ours to call. Hence
# `commune_gst_register_static_plugins`, called from `src/lib.rs` immediately
# after `gst::init()` — the registration functions call
# `gst_plugin_register_static`, which needs an initialized registry.
#
# # Absolute paths, and why not -L
#
# Each plugin drags in third-party libraries: opus needs libopus, mpg123 needs
# libmpg123, and so on. Those live in the tarball's `lib/` next to its own GLib,
# cairo, freetype, libpng and the two dozen other libraries pixiewood also
# builds. Adding that directory with `-L` is exactly the shadowing that
# `gstreamer-prefix.sh` exists to prevent — the linker searches `-L`
# directories in order for *every* `-l` on the line, so one `-L` here would let
# the tarball answer `-lglib-2.0` again.
#
# So nothing is emitted as `-L` plus `-l`. Every archive is named by its
# absolute path, which the linker takes as a file rather than a search, and
# which therefore cannot answer anybody else's `-l`.
#
# The dependencies themselves come from the `.la` files beside each archive.
# Their `dependency_libs` are absolute paths into Cerbero's build machine
# (`/home/nirbheek/...`) and so are useless as paths, but their basenames are
# exactly the dependency graph, and resolving those against `deps/` is what the
# loop below does.
#
# Names in `SKIP` are the ones pixiewood already provides as shared libraries.
# They stay unresolved here on purpose, so that the `-l` flags already on the
# link line — from `android_deps` — answer them, and there is one GLib in the
# process rather than two.
set -eu

prefix=${1:-}
list=${2:-}
mode=${3:-}
if [ -z "$prefix" ] || [ -z "$list" ] || [ -z "$mode" ]; then
	echo "usage: $0 <prefix-arch-dir> <plugin-list> --libs|--source" >&2
	exit 2
fi
deps="$prefix/deps"

plugins=$(sed 's/#.*//' "$list" | tr -s ' \t' ' ' | tr ' ' '\n' | grep -v '^$')

if [ "$mode" = "--source" ]; then
	cat <<'HEADER'
/* Generated by build-aux/android/gstreamer-static-plugins.sh. Do not edit.
 *
 * The plugin list is build-aux/android/gstreamer-plugins.
 */

#include <gst/gst.h>

HEADER
	for p in $plugins; do
		echo "GST_PLUGIN_STATIC_DECLARE($p);"
	done
	cat <<'MID'

void commune_gst_register_static_plugins (void);

/* Called from src/lib.rs, right after gst::init(). Nothing is discovered in a
 * static build: an element whose plugin is not registered here does not exist.
 */
void
commune_gst_register_static_plugins (void)
{
MID
	for p in $plugins; do
		echo "  GST_PLUGIN_STATIC_REGISTER($p);"
	done
	echo "}"
	exit 0
fi

if [ "$mode" != "--libs" ]; then
	echo "$0: unknown mode $mode" >&2
	exit 2
fi

# Provided by pixiewood as shared libraries; must not be answered from here.
SKIP=" glib-2.0 gobject-2.0 gio-2.0 gmodule-2.0 gthread-2.0 intl ffi pcre2-8 z "

work=$(mktemp)
seen=$(mktemp)
out=$(mktemp)
trap 'rm -f "$work" "$seen" "$out"' EXIT

for p in $plugins; do
	if [ ! -f "$deps/libgst$p.a" ]; then
		echo "$0: no plugin '$p' at $deps/libgst$p.a" >&2
		exit 1
	fi
	echo "libgst$p" >> "$work"
done

# Breadth-first over `.la` dependency_libs. Plugins are emitted before the
# libraries they need, which is the order a left-to-right linker wants.
#
# No --start-group here, though GStreamer's own libraries do have cycles between
# them: Meson already wraps the entire link in one, and lld rejects a nested
# group outright — "error: nested --start-group".
while [ -s "$work" ]; do
	name=$(head -n 1 "$work")
	sed -i '1d' "$work"

	grep -qxF "$name" "$seen" 2>/dev/null && continue
	echo "$name" >> "$seen"

	case "$SKIP" in
	*" ${name#lib} "*) continue ;;
	esac

	archive="$deps/$name.a"
	[ -f "$archive" ] || continue
	echo "$archive" >> "$out"

	la="$deps/$name.la"
	[ -f "$la" ] || continue
	sed -n "s/^dependency_libs='\(.*\)'$/\1/p" "$la" \
		| tr ' ' '\n' \
		| sed -n 's/\.la$//p' \
		| while read -r dep; do
			echo "$(basename "$dep")" >> "$work"
		done
done

cat "$out"
